name: agent
on:
  issues:
    types: [opened, edited]
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GEN page from Issue title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          set -euo pipefail
          echo "== agent start =="
          title="$ISSUE_TITLE"
          body="${ISSUE_BODY:-}"
          cmd="$(printf '%s\n%s' "$title" "$body" | tr '[:upper:]' '[:lower:]')"
          echo "TITLE: $title"
          echo "CMD  : ${cmd:0:120}..."

          # match: GEN: page /slug
          if [[ "$cmd" =~ ^gen:\ *page\ *(/[a-z0-9/_-]+) ]]; then
            slug="${BASH_REMATCH[1]#/}"
            echo "Create route: /$slug"
          else
            echo "No 'GEN: page /...' command. Exit."
            exit 0
          fi

          # choose Next base dir (prefer app router)
          if [ -d app ]; then base=app
          elif [ -d src/app ]; then base=src/app
          elif [ -d src/pages ]; then base=src/pages
          elif [ -d pages ]; then base=pages
          else base=app; fi
          mkdir -p "$base"
          echo "BASE : $base"

          # compute target path
          if [[ "$base" == *pages ]]; then
            path="$base/${slug}.tsx"
          else
            path="$base/$slug/page.tsx"
          fi
          echo "TARGET: $path"

          # no-op if exists
          if [ -f "$path" ]; then
            echo "Already exists → $path"
            exit 0
          fi

          # write page
          mkdir -p "$(dirname "$path")"
          cat > "$path" <<'TSX'
          export default function Page() {
            return (
              <main>
                <h1>__ROUTE__</h1>
                <p>Auto-generated.</p>
              </main>
            );
          }
          TSX
          sed -i "s|__ROUTE__|/${slug}|g" "$path"
          echo "WROTE: $path"

          # commit only if changed
          git config user.name "agent-bot"
          git config user.email "agent-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No staged changes."
            exit 0
          fi
          git commit -m "agent: add page /$slug"
          git push
          echo "== agent done =="
