name: agent

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Next.js page from issue title
        shell: bash
        run: |
          set -euo pipefail
          echo "== Agent start =="

          title="${{ github.event.issue.title }}"
          body="${{ github.event.issue.body || '' }}"
          echo "TITLE: $title"
          echo "BODY  : ${body:0:60}..."

          # Lowercase “GEN: page /slug” command detection
          cmd="$(printf '%s\n%s' "$title" "$body" | tr 'A-Z' 'a-z')"
          if [[ "$cmd" =~ ^gen:\ *page\ *(/[a-z0-9/_-]+) ]]; then
            slug="${BASH_REMATCH[1]#/}"
            echo "Detected command → create route: /$slug"
          else
            echo "No 'GEN: page /...' command found. Done."
            exit 0
          fi

          # Pick base dir (prefer app router)
          if [ -d app ]; then base=app
          elif [ -d src/app ]; then base=src/app
          elif [ -d src/pages ]; then base=src/pages
          else base=pages; fi
          echo "Using base dir: $base"

          # Compute file path
          if [[ "$base" == *pages ]]; then
            path="$base/${slug}.tsx"
          else
            path="$base/$slug/page.tsx"
          fi
          echo "Target file: $path"

          # Skip if already exists
          if [ -f "$path" ]; then
            echo "Page already exists → $path (nothing to do)."
            exit 0
          fi

          # Write file
          mkdir -p "$(dirname "$path")"
          cat > "$path" <<'TSX'
          export default function Page(){
            return (
              <main style={{ padding: 24 }}>
                <h1>REPLACEME</h1>
                <p>Auto-generated.</p>
              </main>
            );
          }
          TSX
          sed -i "s|REPLACEME|/${slug}|g" "$path"
          echo "WROTE: $path"

          # Commit only if there are changes
          git config user.name "agent-bot"
          git config user.email "agent-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes staged. Exiting successfully."
            exit 0
          fi
          git commit -m "agent: add page /$slug from issue #${{ github.event.issue.number }}"
          git push
          echo "== Agent done =="
