name: agent-issue-runner
on:
  issues: { types: [opened, edited] }
permissions:
  contents: write
  pull-requests: write
jobs:
  make-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Parse issue and generate change
        env: { GITHUB_EVENT: ${{ toJson(github.event) }} }
        run: |
          python - <<'PY'
          import os, json, re, pathlib
          ev=json.loads(os.environ['GITHUB_EVENT'])
          title=(ev.get('issue',{}).get('title') or '').strip()
          body =(ev.get('issue',{}).get('body')  or '')
          cmd=(title+"\n"+body).lower()
          base=pathlib.Path('.'); changed=False
          def ensure(p,txt):
              p.parent.mkdir(parents=True, exist_ok=True); p.write_text(txt, encoding='utf-8')
          m=re.search(r'gen:\s*page\s*([/\w\-]+)', cmd)  # GEN: page /hello
          if m:
            slug=m.group(1).strip('/')
            for c in ['src/app','app','src/pages','pages']:
              if (base/c).exists(): root=c; break
            else:
              root='app'; (base/root).mkdir(parents=True, exist_ok=True)
            if 'pages' in root:
              path=base/root/(slug+'.tsx'); ensure(path, f"export default function Page(){{return(<main><h1>/{slug}</h1><p>Auto-generated.</p></main>);}}")
            else:
              path=base/root/slug/'page.tsx'; ensure(path, "export default function Page(){return(<main><h1>/" + slug + "</h1><p>Auto-generated.</p></main>);}")
            changed=True
          open('_CHANGED.flag','w').write('1' if changed else '0')
          PY
      - name: Open Pull Request
        if: ${{ hashFiles('_CHANGED.flag') != '' }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "agent: apply issue #${{ github.event.issue.number }}"
          branch: "agent/issue-${{ github.event.issue.number }}"
          title: "Agent change from issue #${{ github.event.issue.number }}"
          body: "Auto-generated change based on issue #${{ github.event.issue.number }}."
