name: seed-once
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Seed minimal Next.js app to main if missing
        run: |
          if [ -f package.json ]; then
            echo "Already seeded, nothing to do."; exit 0
          fi

          mkdir -p app

          cat > package.json <<'EOF'
          {
            "name": "weave-dashboard",
            "private": true,
            "version": "0.1.0",
            "scripts": {
              "dev": "next dev",
              "build": "next build",
              "start": "next start",
              "lint": "next lint"
            },
            "dependencies": {
              "next": "^14.2.5",
              "react": "^18.2.0",
              "react-dom": "^18.2.0"
            }
          }
          EOF

          cat > next.config.mjs <<'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = { experimental: { appDir: true } };
          export default nextConfig;
          EOF

          cat > tsconfig.json <<'EOF'
          {
            "compilerOptions": {
              "target": "ES2020",
              "lib": ["dom", "dom.iterable", "esnext"],
              "allowJs": true,
              "skipLibCheck": true,
              "strict": false,
              "noEmit": true,
              "module": "esnext",
              "moduleResolution": "bundler",
              "resolveJsonModule": true,
              "isolatedModules": true,
              "jsx": "preserve",
              "plugins": [{ "name": "next" }]
            },
            "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.cjs"],
            "exclude": ["node_modules"]
          }
          EOF

          cat > next-env.d.ts <<'EOF'
          /// <reference types="next" />
          /// <reference types="next/image-types/global" />
          EOF

          cat > .gitignore <<'EOF'
          node_modules
          .next
          out
          EOF

          cat > app/layout.tsx <<'EOF'
          export default function RootLayout({ children }: { children: React.ReactNode }) {
            return (
              <html lang="en">
                <body style={{ fontFamily: "system-ui, Arial", padding: 24 }}>{children}</body>
              </html>
            );
          }
          EOF

          cat > app/page.tsx <<'EOF'
          export default function Page() {
            return (
              <main style={{ padding: 24 }}>
                <h1>Dashboard</h1>
                <p>Seeded by CI.</p>
              </main>
            );
          }
          EOF

          git config user.name "seed-bot"
          git config user.email "seed-bot@users.noreply.github.com"
          git add -A
          git commit -m "chore(seed): initial Next.js skeleton"
          git push
